drop table if exists t_task;
drop table if exists t_user;

    drop table t_sys_menu if exists;

    drop table t_sys_menu_perm_rela if exists;
    
 drop table t_sys_permission if exists;

    drop table t_sys_permission_resource_perm_relas if exists;

    drop table t_sys_resource if exists;

    drop table t_sys_resource_perm_rela if exists;

    drop table t_sys_resource_resource_perm_relas if exists;

    drop table t_sys_role if exists;

    drop table t_sys_role_perm_rela if exists;

    drop table t_sys_role_role_perm_relas if exists;

create table t_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

create table t_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);

    create table t_sys_menu (
        id bigint generated by default as identity,
        enable_flg boolean not null,
        menu_name varchar(255),
        remark varchar(255),
        url varchar(255),
        parent_id bigint,
        primary key (id)
    );

    create table t_sys_menu_perm_rela (
        id bigint generated by default as identity,
        menu_id bigint,
        permission_id bigint,
        primary key (id)
    );
    create table t_sys_permission (
        id bigint generated by default as identity,
        perm_cd varchar(255),
        perm_name varchar(255),
        remark varchar(255),
        primary key (id)
    );

    create table t_sys_permission_resource_perm_relas (
        t_sys_permission bigint not null,
        resource_perm_relas bigint not null,
        unique (resource_perm_relas)
    );

  
    create table t_sys_resource (
        id bigint generated by default as identity,
        enable_flg boolean not null,
        remark varchar(255),
        url varchar(255),
        primary key (id)
    );
    
    create table t_sys_resource_perm_rela (
        id bigint generated by default as identity,
        permission_id bigint,
        resource_id bigint,
        primary key (id)
    );

    create table t_sys_resource_resource_perm_relas (
        t_sys_resource bigint not null,
        resource_perm_relas bigint not null,
        unique (resource_perm_relas)
    );

    create table t_sys_role (
        id bigint generated by default as identity,
        remark varchar(255),
        role_cd varchar(255),
        role_name varchar(255),
        primary key (id)
    );

    create table t_sys_role_perm_rela (
        id bigint generated by default as identity,
        permission_id bigint,
        role_id bigint,
        primary key (id)
    );

    create table t_sys_role_role_perm_relas (
        t_sys_role bigint not null,
        role_perm_relas bigint not null,
        unique (role_perm_relas)
    );
    
        alter table t_sys_menu 
        add constraint FK2B50BAFCD6BD67C6 
        foreign key (parent_id) 
        references t_sys_menu;

    alter table t_sys_menu_perm_rela 
        add constraint FKD14F215493FC22F1 
        foreign key (menu_id) 
        references t_sys_menu;

    alter table t_sys_menu_perm_rela 
        add constraint FKD14F2154BFC13FB1 
        foreign key (permission_id) 
        references t_sys_permission;

    alter table t_sys_resource_perm_rela 
        add constraint FK19B08AC3BFC13FB1 
        foreign key (permission_id) 
        references t_sys_permission;

    alter table t_sys_resource_perm_rela 
        add constraint FK19B08AC32BFC4D11 
        foreign key (resource_id) 
        references t_sys_resource;

    alter table t_sys_role_perm_rela 
        add constraint FK2E13DBABAD6AB791 
        foreign key (role_id) 
        references t_sys_role;

    alter table t_sys_role_perm_rela 
        add constraint FK2E13DBABBFC13FB1 
        foreign key (permission_id) 
        references t_sys_permission;
